(cl:in-package robots_msg-msg)
(cl:export '(TYPE-VAL
          TYPE
          IP-VAL
          IP
          PORT-VAL
          PORT
          ID-VAL
          ID
          INST_BEFORE-VAL
          INST_BEFORE
          BATTERY-VAL
          BATTERY
          SERVO0-VAL
          SERVO0
          SERVO1-VAL
          SERVO1
          SERVO2-VAL
          SERVO2
          SERVO3-VAL
          SERVO3
          SERVO4-VAL
          SERVO4
          SERVO5-VAL
          SERVO5
          CAMERA-VAL
          CAMERA
          MAGNET-VAL
          MAGNET
          STATUS-VAL
          STATUS
))