(cl:in-package robots_msg-msg)
(cl:export '(TYPE-VAL
          TYPE
          IP-VAL
          IP
          PORT-VAL
          PORT
          ID-VAL
          ID
          INST_BEFORE-VAL
          INST_BEFORE
          BASE_SPEED-VAL
          BASE_SPEED
          BASE_TARGET-VAL
          BASE_TARGET
          BASE_CURRENT-VAL
          BASE_CURRENT
          LEFT_SPEED-VAL
          LEFT_SPEED
          LEFT_TARGET-VAL
          LEFT_TARGET
          LEFT_CURRENT-VAL
          LEFT_CURRENT
          RIGHT_SPEED-VAL
          RIGHT_SPEED
          RIGHT_TARGET-VAL
          RIGHT_TARGET
          RIGHT_CURRENT-VAL
          RIGHT_CURRENT
          COLOR-VAL
          COLOR
          GRIPPER-VAL
          GRIPPER
          STATUS-VAL
          STATUS
))