(cl:in-package robots_msg-msg)
(cl:export '(TYPE-VAL
          TYPE
          IP-VAL
          IP
          PORT-VAL
          PORT
          ID-VAL
          ID
          INST_BEFORE-VAL
          INST_BEFORE
          BATTERY-VAL
          BATTERY
          RANGE_C-VAL
          RANGE_C
          COMPAS-VAL
          COMPAS
          MOTOR1-VAL
          MOTOR1
          MOTOR3-VAL
          MOTOR3
          MOTOR2-VAL
          MOTOR2
          MOTOR4-VAL
          MOTOR4
          JEVOIS-VAL
          JEVOIS
          PLAT-VAL
          PLAT
          STATUS-VAL
          STATUS
))