// Generated by gencpp from file robots_msg/DiscreteAction.msg
// DO NOT EDIT!


#ifndef ROBOTS_MSG_MESSAGE_DISCRETEACTION_H
#define ROBOTS_MSG_MESSAGE_DISCRETEACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robots_msg
{
template <class ContainerAllocator>
struct DiscreteAction_
{
  typedef DiscreteAction_<ContainerAllocator> Type;

  DiscreteAction_()
    : robot_id()
    , action()  {
    }
  DiscreteAction_(const ContainerAllocator& _alloc)
    : robot_id(_alloc)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_id_type;
  _robot_id_type robot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::robots_msg::DiscreteAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_msg::DiscreteAction_<ContainerAllocator> const> ConstPtr;

}; // struct DiscreteAction_

typedef ::robots_msg::DiscreteAction_<std::allocator<void> > DiscreteAction;

typedef boost::shared_ptr< ::robots_msg::DiscreteAction > DiscreteActionPtr;
typedef boost::shared_ptr< ::robots_msg::DiscreteAction const> DiscreteActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_msg::DiscreteAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_msg::DiscreteAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robots_msg::DiscreteAction_<ContainerAllocator1> & lhs, const ::robots_msg::DiscreteAction_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robots_msg::DiscreteAction_<ContainerAllocator1> & lhs, const ::robots_msg::DiscreteAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robots_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robots_msg::DiscreteAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_msg::DiscreteAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_msg::DiscreteAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_msg::DiscreteAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_msg::DiscreteAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_msg::DiscreteAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_msg::DiscreteAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b521f11e88571246b003b95decc73bfa";
  }

  static const char* value(const ::robots_msg::DiscreteAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb521f11e88571246ULL;
  static const uint64_t static_value2 = 0xb003b95decc73bfaULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_msg::DiscreteAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_msg/DiscreteAction";
  }

  static const char* value(const ::robots_msg::DiscreteAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_msg::DiscreteAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Provide information about the type of action the robot will perform\n"
"string robot_id # robot id\n"
"string action # discrete action\n"
;
  }

  static const char* value(const ::robots_msg::DiscreteAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_msg::DiscreteAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiscreteAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_msg::DiscreteAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_msg::DiscreteAction_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_id);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_MSG_MESSAGE_DISCRETEACTION_H
