// Generated by gencpp from file robots_msg/lidar.msg
// DO NOT EDIT!


#ifndef ROBOTS_MSG_MESSAGE_LIDAR_H
#define ROBOTS_MSG_MESSAGE_LIDAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robots_msg
{
template <class ContainerAllocator>
struct lidar_
{
  typedef lidar_<ContainerAllocator> Type;

  lidar_()
    : position(0)
    , range(0)  {
    }
  lidar_(const ContainerAllocator& _alloc)
    : position(0)
    , range(0)  {
  (void)_alloc;
    }



   typedef int16_t _position_type;
  _position_type position;

   typedef int16_t _range_type;
  _range_type range;





  typedef boost::shared_ptr< ::robots_msg::lidar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_msg::lidar_<ContainerAllocator> const> ConstPtr;

}; // struct lidar_

typedef ::robots_msg::lidar_<std::allocator<void> > lidar;

typedef boost::shared_ptr< ::robots_msg::lidar > lidarPtr;
typedef boost::shared_ptr< ::robots_msg::lidar const> lidarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_msg::lidar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_msg::lidar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robots_msg::lidar_<ContainerAllocator1> & lhs, const ::robots_msg::lidar_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.range == rhs.range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robots_msg::lidar_<ContainerAllocator1> & lhs, const ::robots_msg::lidar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robots_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robots_msg::lidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_msg::lidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_msg::lidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_msg::lidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_msg::lidar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_msg::lidar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_msg::lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5060fc4ab83a253ef9abef852a44d0ad";
  }

  static const char* value(const ::robots_msg::lidar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5060fc4ab83a253eULL;
  static const uint64_t static_value2 = 0xf9abef852a44d0adULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_msg::lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_msg/lidar";
  }

  static const char* value(const ::robots_msg::lidar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_msg::lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 position\n"
"int16 range\n"
;
  }

  static const char* value(const ::robots_msg::lidar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_msg::lidar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_msg::lidar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_msg::lidar_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.position);
    s << indent << "range: ";
    Printer<int16_t>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_MSG_MESSAGE_LIDAR_H
