(cl:in-package arena_msgs-msg)
(cl:export '(TYPE-VAL
          TYPE
          IP-VAL
          IP
          PORT-VAL
          PORT
          ID-VAL
          ID
          INST_BEFORE-VAL
          INST_BEFORE
          BATTERY-VAL
          BATTERY
          TEMPE-VAL
          TEMPE
          LINE0-VAL
          LINE0
          LINE1-VAL
          LINE1
          MOTOR1-VAL
          MOTOR1
          MOTOR2-VAL
          MOTOR2
          CAMERA-VAL
          CAMERA
          SENSOR_LIDAR-VAL
          SENSOR_LIDAR
          STATUS-VAL
          STATUS
))