(cl:in-package arena_msgs-msg)
(cl:export '(TYPE-VAL
          TYPE
          IP-VAL
          IP
          PORT-VAL
          PORT
          ID-VAL
          ID
          INST_BEFORE-VAL
          INST_BEFORE
          BATTERY-VAL
          BATTERY
          RANGE_L-VAL
          RANGE_L
          RANGE_C-VAL
          RANGE_C
          RANGE_R-VAL
          RANGE_R
          COMPAS-VAL
          COMPAS
          POS_MOTOR1-VAL
          POS_MOTOR1
          POS_MOTOR2-VAL
          POS_MOTOR2
          JEVOIS-VAL
          JEVOIS
          STATUS-VAL
          STATUS
))