# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robots_msg/eco_msgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robots_msg.msg

class eco_msgs(genpy.Message):
  _md5sum = "b06ae61beeb797a599af8e0764bf224c"
  _type = "robots_msg/eco_msgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string type  # type of robot “ECOLOGY20”
string ip  # address of the robot ESP8866
uint32 port  # port for comunication
uint8 id  # uint8_t id of the robot
uint8 inst_before  # the last instruction runner 
float32 battery  # % of the battery
uint16 range_l  # left ir sensor
uint16 range_c  # laser sensor
uint16 range_r  # right ir sensor 
int16 compas  # heading
int16 pos_motor1  # position motor left
int16 pos_motor2  # position motor right 
robots_msg/camera jevois  # Aruco info
string status  # "Completed" or "Error type 1"

================================================================================
MSG: robots_msg/camera
int8 detect  # 1 : detect, 0 : non detect    
uint8 id  # id of fiducial
int16 targx  # coordinate x
int16 targy  # coordinate y
string data  # all info in string
"""
  __slots__ = ['type','ip','port','id','inst_before','battery','range_l','range_c','range_r','compas','pos_motor1','pos_motor2','jevois','status']
  _slot_types = ['string','string','uint32','uint8','uint8','float32','uint16','uint16','uint16','int16','int16','int16','robots_msg/camera','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,ip,port,id,inst_before,battery,range_l,range_c,range_r,compas,pos_motor1,pos_motor2,jevois,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(eco_msgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = ''
      if self.ip is None:
        self.ip = ''
      if self.port is None:
        self.port = 0
      if self.id is None:
        self.id = 0
      if self.inst_before is None:
        self.inst_before = 0
      if self.battery is None:
        self.battery = 0.
      if self.range_l is None:
        self.range_l = 0
      if self.range_c is None:
        self.range_c = 0
      if self.range_r is None:
        self.range_r = 0
      if self.compas is None:
        self.compas = 0
      if self.pos_motor1 is None:
        self.pos_motor1 = 0
      if self.pos_motor2 is None:
        self.pos_motor2 = 0
      if self.jevois is None:
        self.jevois = robots_msg.msg.camera()
      if self.status is None:
        self.status = ''
    else:
      self.type = ''
      self.ip = ''
      self.port = 0
      self.id = 0
      self.inst_before = 0
      self.battery = 0.
      self.range_l = 0
      self.range_c = 0
      self.range_r = 0
      self.compas = 0
      self.pos_motor1 = 0
      self.pos_motor2 = 0
      self.jevois = robots_msg.msg.camera()
      self.status = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I2Bf3H3hbB2h().pack(_x.port, _x.id, _x.inst_before, _x.battery, _x.range_l, _x.range_c, _x.range_r, _x.compas, _x.pos_motor1, _x.pos_motor2, _x.jevois.detect, _x.jevois.id, _x.jevois.targx, _x.jevois.targy))
      _x = self.jevois.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.jevois is None:
        self.jevois = robots_msg.msg.camera()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ip = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.port, _x.id, _x.inst_before, _x.battery, _x.range_l, _x.range_c, _x.range_r, _x.compas, _x.pos_motor1, _x.pos_motor2, _x.jevois.detect, _x.jevois.id, _x.jevois.targx, _x.jevois.targy,) = _get_struct_I2Bf3H3hbB2h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.jevois.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.jevois.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I2Bf3H3hbB2h().pack(_x.port, _x.id, _x.inst_before, _x.battery, _x.range_l, _x.range_c, _x.range_r, _x.compas, _x.pos_motor1, _x.pos_motor2, _x.jevois.detect, _x.jevois.id, _x.jevois.targx, _x.jevois.targy))
      _x = self.jevois.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.jevois is None:
        self.jevois = robots_msg.msg.camera()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ip = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.port, _x.id, _x.inst_before, _x.battery, _x.range_l, _x.range_c, _x.range_r, _x.compas, _x.pos_motor1, _x.pos_motor2, _x.jevois.detect, _x.jevois.id, _x.jevois.targx, _x.jevois.targy,) = _get_struct_I2Bf3H3hbB2h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.jevois.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.jevois.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I2Bf3H3hbB2h = None
def _get_struct_I2Bf3H3hbB2h():
    global _struct_I2Bf3H3hbB2h
    if _struct_I2Bf3H3hbB2h is None:
        _struct_I2Bf3H3hbB2h = struct.Struct("<I2Bf3H3hbB2h")
    return _struct_I2Bf3H3hbB2h
