# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robots_msg/xl320.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class xl320(genpy.Message):
  _md5sum = "67fe2fb91485e549cd0ff16b0e5b40e4"
  _type = "robots_msg/xl320"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8  ID
uint8  LED
uint16 speed
uint16 Goal_Position
uint16 Present_Position
"""
  __slots__ = ['ID','LED','speed','Goal_Position','Present_Position']
  _slot_types = ['uint8','uint8','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,LED,speed,Goal_Position,Present_Position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(xl320, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.LED is None:
        self.LED = 0
      if self.speed is None:
        self.speed = 0
      if self.Goal_Position is None:
        self.Goal_Position = 0
      if self.Present_Position is None:
        self.Present_Position = 0
    else:
      self.ID = 0
      self.LED = 0
      self.speed = 0
      self.Goal_Position = 0
      self.Present_Position = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B3H().pack(_x.ID, _x.LED, _x.speed, _x.Goal_Position, _x.Present_Position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.ID, _x.LED, _x.speed, _x.Goal_Position, _x.Present_Position,) = _get_struct_2B3H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B3H().pack(_x.ID, _x.LED, _x.speed, _x.Goal_Position, _x.Present_Position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.ID, _x.LED, _x.speed, _x.Goal_Position, _x.Present_Position,) = _get_struct_2B3H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3H = None
def _get_struct_2B3H():
    global _struct_2B3H
    if _struct_2B3H is None:
        _struct_2B3H = struct.Struct("<2B3H")
    return _struct_2B3H
